- id: addlicense
  name: addlicense
  description: Add copyright license header to source code.
  entry: addlicense
  types: [text]
  language: golang
  minimum_pre_commit_version: 3.0.0
  require_serial: true
